// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mysocietywebsite.Model.ApplicationDbContext;

namespace mysocietywebsite.Model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220116102157_initial-migration")]
    partial class initialmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mysocietywebsite.Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            CreatedBy = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            CreatedOn = new DateTime(2022, 1, 16, 10, 21, 55, 3, DateTimeKind.Utc).AddTicks(4001),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            ModifiedOn = new DateTime(2022, 1, 16, 10, 21, 55, 3, DateTimeKind.Utc).AddTicks(5320),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("c90cea60-7517-414d-822e-74677528a0f7"),
                            CreatedBy = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            CreatedOn = new DateTime(2022, 1, 16, 10, 21, 55, 3, DateTimeKind.Utc).AddTicks(6012),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            ModifiedOn = new DateTime(2022, 1, 16, 10, 21, 55, 3, DateTimeKind.Utc).AddTicks(6060),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("mysocietywebsite.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0c6b13e0-0f19-45ae-8fac-f6f3293284ef"),
                            Address = "H.No - 30 Indus Town",
                            Contact = "9109072549",
                            CreatedBy = new Guid("0c6b13e0-0f19-45ae-8fac-f6f3293284ef"),
                            CreatedOn = new DateTime(2022, 1, 16, 10, 21, 56, 963, DateTimeKind.Utc).AddTicks(5771),
                            Email = "tarun@gmail.com",
                            Fullname = "Tarunendra",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("0c6b13e0-0f19-45ae-8fac-f6f3293284ef"),
                            ModifiedOn = new DateTime(2022, 1, 16, 10, 21, 56, 963, DateTimeKind.Utc).AddTicks(5844),
                            Password = "BJJcVkTHd9Qkv8iCM8srzsyU50CjkRe4ckHbWkHVlAc=",
                            RoleId = new Guid("92235171-06b3-40e6-adaf-2499bbe3b4f0"),
                            Username = "AD"
                        });
                });

            modelBuilder.Entity("mysocietywebsite.Model.Entities.User", b =>
                {
                    b.HasOne("mysocietywebsite.Model.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
