// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mysocietywebsite.Model.ApplicationDbContext;

namespace mysocietywebsite.Model.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220114144159_SecondMigration")]
    partial class SecondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("mysocietywebsite.Model.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bfa65a33-79e5-4eb9-ad35-6a73ac0172d7"),
                            CreatedBy = new Guid("bfa65a33-79e5-4eb9-ad35-6a73ac0172d7"),
                            CreatedOn = new DateTime(2022, 1, 14, 14, 41, 59, 337, DateTimeKind.Utc).AddTicks(9073),
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("bfa65a33-79e5-4eb9-ad35-6a73ac0172d7"),
                            ModifiedOn = new DateTime(2022, 1, 14, 14, 41, 59, 337, DateTimeKind.Utc).AddTicks(9616),
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("mysocietywebsite.Model.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Contact")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Fullname")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1ef664ec-904b-43c7-87ab-a1bfbd3df8de"),
                            Address = "H.No - 30 Indus Town",
                            Contact = "9109072549",
                            CreatedBy = new Guid("1ef664ec-904b-43c7-87ab-a1bfbd3df8de"),
                            CreatedOn = new DateTime(2022, 1, 14, 14, 41, 59, 339, DateTimeKind.Utc).AddTicks(1899),
                            Email = "tarun@gmail.com",
                            Fullname = "Tarunendra",
                            IsActive = true,
                            IsDeleted = false,
                            ModifiedBy = new Guid("1ef664ec-904b-43c7-87ab-a1bfbd3df8de"),
                            ModifiedOn = new DateTime(2022, 1, 14, 14, 41, 59, 339, DateTimeKind.Utc).AddTicks(1918),
                            Password = "123456789",
                            RoleId = new Guid("bfa65a33-79e5-4eb9-ad35-6a73ac0172d7"),
                            Username = "AD"
                        });
                });

            modelBuilder.Entity("mysocietywebsite.Model.Entities.User", b =>
                {
                    b.HasOne("mysocietywebsite.Model.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
